### ISSUE TITLE
unable to run generator

### ISSUE THREAD

**Issue by jmls** [smnbbrv/ngx-spec#1]
after trying to install with `npm i -D ngx-spec` and then `yarn add -D ngx-spec` (just in case it was an npm problem) I get the following error when running

> ng g spec ngx-spec:spec app.component.ts

```
Schematic "spec" not found in collection "@schematics/angular".
Error: Schematic "spec" not found in collection "@schematics/angular".

```

not sure if I'm missing a step or something

**Comment by smnbbrv** [comment]
Haha. Stupid me. The readme typo, this is the correct commands:

Run:

```sh
ng g ngx-spec:spec path/my.service
```

or

```sh
ng g ngx-spec:spec path/my.service.ts
```

Does this work now?

**Comment by jmls** [comment]
is does indeed ;) thanks

**Comment by jmls** [comment]
enhancement request #1 :)

It would be nice to traverse the app tree, generating all missing specs for all services, components and directives ...

**Comment by smnbbrv** [comment]
Could you create another issue for that?

For now you can use something similar to https://stackoverflow.com/questions/10523415/bash-script-to-execute-command-on-all-files-in-a-directory (should not be complicated). I will hopefully return to the issue next week
