### ISSUE TITLE
"type is not defined" for type "component"

### ISSUE THREAD

**Issue by ffderic** [smnbbrv/ngx-spec#11]
When trying to use "ng g ngx-spec:spec <some.component.ts>" I just get message "type is not defined" and nothing is generated. It works just fine with services...
Is this a known issue? Any idea?
I use version 2.1.4.

**Comment by BrianJVarley** [comment]
Same as @ffderic when I run `ngx-spec` against a component written in typescript. I get the following..

```
$ ng g ngx-spec:spec screen-pops-list.component.ts
type is not defined
```

**Comment by saikiranvadlakonda** [comment]
I'm also facing the same error

![image](https://user-images.githubusercontent.com/14762284/87540185-da7d0880-c6bc-11ea-81f2-05fd401f02d6.png)

Any idea, how to resolve it.

**Comment by buddyackerman** [comment]
Same issue here.  Not sure why the most used type is not supported.  I'm using NG9.

**Comment by lucb-pc** [comment]
I have the exact same problem

**Comment by ThatSpaceGuy** [comment]
+1 Same problem - Is anyone working on this?

**Comment by ThatSpaceGuy** [comment]
I was able to successfully generate a spec file by running `npm i ngx-spec` for the project that I wanted to generate the file in.  Apparently having it installed globally is not enough - once it was part of the particular project, it generated the desired spec file for a 'component'.  Hopefully this helps someone else with the same issues!

**Comment by joguarino** [comment]
Same here, the problem is still present, and neither the solution proposed by @ThatSpaceGuy works for me

**Comment by kylebradshaw** [comment]
unfortunately I think the project is essentially dead, it's a non-starter at this point.

**Comment by smnbbrv** [comment]
This project is something that was created to solve the particular problem several years ago until Angular team comes with a normal solution. However it looks like they still did not.

There is always an option to make a pull request that fixes the issue or take the project for maintenance. Just complaining does not solve the issue...

**Comment by kylebradshaw** [comment]
Agree. Sorry about being so curt. Was working on testing way to late. Thanks for replying to the thread.

**Comment by docsa** [comment]
Issue stems from an incompatibility with  angular version 9. It can be worked around by installing locally  angular-cli@8
Hope this helps

**Comment by cacalo** [comment]
> This project is something that was created to solve the particular problem several years ago until Angular team comes with a normal solution. However it looks like they still did not.
> 
> There is always an option to make a pull request that fixes the issue or take the project for maintenance. Just complaining does not solve the issue...

I fixed the issue and I want to make a pull request. I need permission to upload my branch.
Could you please do that for me?
Thank you!

**Comment by smnbbrv** [comment]
Hi, sounds super!

you can fork the project, make the necessary changes and create a pull request from the fork. This is a normal flow for GitHub projects

**Comment by cacalo** [comment]
Fix already merged! This should not longer be an issue :)
