### ISSUE TITLE
feature request : create all missing specs

### ISSUE THREAD

**Issue by jmls** [smnbbrv/ngx-spec#2]
It would be nice to traverse the app tree, generating all missing specs for all services, components and directives ...

**Comment by jmls** [comment]
having said that, running

`find ./ -type f -name "*.service.*" -exec ng g ngx-spec:spec {} \;`

when in the `src/app` folder works well

**Comment by smnbbrv** [comment]
added glob support with ngx-spec:specs

Please let me know if there are problems especially on windows (cannot easily test it there)
