### ISSUE TITLE
`Schematic "spec" not found in collection "@schematics/angular".

### ISSUE THREAD

**Issue by semla** [smnbbrv/ngx-spec#4]
I am getting `Schematic "spec" not found in collection "@schematics/angular".
Error: Schematic "spec" not found in collection "@schematics/angular"` when I try to run `ng g spec ngx-spec:spec src/app/my-service.service`

**Comment by assafshemesh** [comment]
I am getting `Schematic "ngx-spec:spec" not found in collection "@schematics/angular".`
Angular CLI ver 1.6.4

**Comment by smnbbrv** [comment]
upgrade your angular cli to v6. Versions below are not supported

**Comment by smnbbrv** [comment]
Actually what you can try is `ng generate spec --collection ngx-spec`. This is the syntax for lower versions, however I am not sure it will work fine

**Comment by assafshemesh** [comment]
upgraded angular cli to v6.0.8
now I get an error: `Unknown Protocol on url "[object Object]".`

**Comment by smnbbrv** [comment]
then it relates to #3
