### ISSUE TITLE
Tree type is not supported.

### ISSUE THREAD

**Issue by NikolaMalezanoski** [smnbbrv/ngx-spec#5]
When I run I got this message:
"Tree type is not supported."

Whats the issue

**Comment by smnbbrv** [comment]
Hi @NikolaMalezanoski 

that's really hard to say.

Could you add some info about 

1. your OS
2. command you are running
3. other things you find (your project) specific

**Comment by viktormelnychuk** [comment]
@smnbbrv Hi, I experienced same issue. I have created new project using angular-cli. Then i created new component (`ng g c test --spec=false`). After component was created I run `ng g ngx-spec:spec test/test.component.ts` and got error mentioned above. This issue reproducible on linux and windows. Here are my dependencies:
```
"dependencies": {
    "@angular/animations": "^6.0.3",
    "@angular/common": "^6.0.3",
    "@angular/compiler": "^6.0.3",
    "@angular/core": "^6.0.3",
    "@angular/forms": "^6.0.3",
    "@angular/http": "^6.0.3",
    "@angular/platform-browser": "^6.0.3",
    "@angular/platform-browser-dynamic": "^6.0.3",
    "@angular/router": "^6.0.3",
    "@ng-bootstrap/ng-bootstrap": "^2.2.0",
    "core-js": "^2.5.4",
    "rxjs": "^6.0.0",
    "zone.js": "^0.8.26"
  },
  "devDependencies": {
    "@angular-devkit/build-angular": "~0.6.8",
    "@angular/cli": "~6.0.8",
    "@angular/compiler-cli": "^6.0.3",
    "@angular/language-service": "^6.0.3",
    "@types/jasmine": "~2.8.6",
    "@types/jasminewd2": "~2.0.3",
    "@types/node": "~8.9.4",
    "codelyzer": "~4.2.1",
    "jasmine-core": "~2.99.1",
    "jasmine-spec-reporter": "~4.2.1",
    "karma": "~1.7.1",
    "karma-chrome-launcher": "~2.2.0",
    "karma-coverage-istanbul-reporter": "~2.0.0",
    "karma-jasmine": "~1.1.1",
    "karma-jasmine-html-reporter": "^0.2.2",
    "ngx-spec": "^1.0.0",
    "protractor": "~5.3.0",
    "ts-node": "~5.0.1",
    "tslint": "~5.9.1",
    "typescript": "~2.7.2"
  }
```
And following is the output of `ng -v`:
![image](https://user-images.githubusercontent.com/24207017/43079662-5e780092-8e96-11e8-96cd-31d97816c981.png)

**Comment by smnbbrv** [comment]
Check @1.0.1, should be fixed now.
